package repositoriomineria;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Ocampo Mora
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    JComboBox comboHosts = new JComboBox();
    DefaultComboBoxModel model = new DefaultComboBoxModel();
    InetAddress ip = null;
    String ipHost;
    
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(getIconImage());
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        comboHosts = new JComboBox(model);
        comboHosts.setBackground(new Color(255,255,255));
        comboHosts.setFont(new Font("Arial", Font.BOLD, 14));
        comboHosts.setBounds(90, 85, 230, 23);
        
        try{
            ip = InetAddress.getLocalHost();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        if(model.getIndexOf(ip.getHostName()) == -1){
            comboHosts.addItem("Local: " + ip.getHostName());
        }
        jLabelFondo.add(comboHosts);
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cascoIcon.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JButton();
        jLabelIcon = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonSesion = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Servidor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        botonCrearCuenta.setBackground(new java.awt.Color(0, 255, 0));
        botonCrearCuenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(botonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casco.png"))); // NOI18N
        getContentPane().add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 250, 250));

        jLabelUser.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelUser.setText("Usuario :");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabelPass.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelPass.setText("Contraseña :");
        getContentPane().add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jTextFieldUser.setBackground(new java.awt.Color(255, 255, 51));
        jTextFieldUser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 200, 30));

        jPassword.setBackground(new java.awt.Color(255, 255, 102));
        jPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 200, 30));

        jButtonSesion.setBackground(new java.awt.Color(253, 193, 1));
        jButtonSesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSesion.setText("Iniciar Sesión");
        jButtonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        jLabelName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabelName.setText("Repositorio Herramientas de Mineria");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 430, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jButtonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSesionActionPerformed
        
        String user = jTextFieldUser.getText().trim();
        String password = jPassword.getText().trim();
        
        String host = comboHosts.getSelectedItem().toString();
        
        if(host.toLowerCase().contains("Local: ".toLowerCase())){
            host = host.replace("Local: ", "");
        }
        
        ip = Conexion.getHostIP(host);
        ipHost = ip.getHostAddress();
        
        if(jTextFieldUser.getText().length() == 0 || jPassword.getPassword().length == 0){
            JOptionPane.showMessageDialog(this, "Usuario o contraseña no ingresado");
            jTextFieldUser.setText("");
            jPassword.setText("");
        }
        else{
            try{
                Connection cn = new Conexion(ipHost).conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select id_usuario, username, contrasenia, rol from usuarios where username = '" 
                        + user + "' and contrasenia = '" + password + "'");
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    String id_usuario = rs.getString("id_usuario");
                    String username = rs.getString("username");
                    //String contrasenia = rs.getString("contrasenia");
                    String rol = rs.getString("rol");
                    dispose();
                    new PantallaPrincipal(id_usuario, username, rol, ipHost).setVisible(true);
                }
                else{
                    jPassword.setText("");
                    jTextFieldUser.setText("");
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                }
                cn.close();
                pst.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "No se puede entablar conexión con el servidor.");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButtonSesionActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        try{
            String host = comboHosts.getSelectedItem().toString();
        
            if(host.toLowerCase().contains("Local: ".toLowerCase())){
                host = host.replace("Local: ", "");
            }

            ip = Conexion.getHostIP(host);
            ipHost = ip.getHostAddress();
            new AgregarUsuarios(ipHost).setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se puede entablar conexión con el servidor.");
        }
    }//GEN-LAST:event_botonCrearCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JButton jButtonSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
